### ISSUE TITLE
python 2 not supported anymore?

### ISSUE THREAD

**Issue by pchampin** [maparent/virtuoso-python#11]
I just updated from github, and my Python2 code does not work anymore.
```
  File ".../virtuoso/vstore.py", line 4, in <module>
    from builtins import (next, chr, zip, range, object)
```

Is it a bug or a feature, i.e. Is the lib now only supposed to work with Python3?

**Comment by maparent** [comment]
Clearly a bug, I'll have a look shortly.

**Comment by maparent** [comment]
did you reinstall the content of requirements.txt? It looks like you may be missing future.
I have a few tests failing, but most things do work for me now.

**Comment by pchampin** [comment]
> did you reinstall the content of requirements.txt?

I did a ``pip install --upgrade``, which I expect to install all required dependencies...

I had a look at ``setup.py``, and that confuses me a bit:
* ``setup.py`` uses deprecated options ``requires`` and ``dependency_links``, while it should use ``install_requires``
* dependencies in ``setup.py`` and ``requirements.txt`` are not in sync; I assume that ``requirements.txt`` is the correct list, but I need you to confirm that.

I started updating ``setup.py`` accordingly, but then I realized that ``install_requires`` does not support github URLS :-( It might be possible by keeping the ``dependency_links`` keyword, and forcing pip to use it, using the option ``--process-dependency-links``, although I didn't manage to make that work yet. And even if we do manage eventually, that should at the very least be documented in the README...

**Comment by maparent** [comment]
I added a note in the README about using pip, and made sure that setup.py was better aligned to requirements.txt. Do you think that solves the problem?

**Comment by pchampin** [comment]
Works for me
