### ISSUE TITLE
I have a question: driver's path for odbc.ini for virtuoso docker

### ISSUE THREAD

**Issue by jtrillos** [maparent/virtuoso-python#13]
If I am using a virtuoso docker, how can access the driver's path for odbc.ini configuration?

[VOS]
Description     = Virtuoso
Driver          = ???
Servername      = localhost
Port            = 1111
UserName        = dba
Locale          = en.UTF-8

Thank you

**Comment by maparent** [comment]
You would certainly have to either build the virtuoso driver, or pull it from the docker file (assuming compatible OS between the docker images.) I don't know how well the docker model applies the virtuoso.

**Comment by jtrillos** [comment]
Thanks
