### ISSUE TITLE
Question - what Virtuoso supported and why special pyodbc

### ISSUE THREAD

**Issue by danizen** [maparent/virtuoso-python#16]
* What versions of Virtuoso are supported?   I have 7.2 at the time of this writing.
* Why are patches to pyodbc required?   I have successfully done SPARQL SELECT queries to Virtuoso using standard pyodbc, and so I imagine that marshalling might be required.

**Comment by maparent** [comment]
I tested this code in the Virtuoso 7.0 days, I am not working with it now, so I cannot guarantee support. Some other users of the library should chime in.
I'm frankly surprised that things worked for you with a standard pyodbc; were you just returning literals? You may get literals without their type and language information in that case. Run the test suite and see what breaks?

**Comment by danizen** [comment]
Ah - I don't mean that I tested your package with standard pyodbc, I mean that I can do a SPARQL SELECT against pyodbc.   But, your point about IRIs and language explains.   I'm just getting back literals even when I query subjects...

How then do I go about installing this?

**Comment by danizen** [comment]
> How then do I go about installing this?

I'll use git submodule, and my `requirements.txt` will point to `virtuoso-python/dist/something.whl`.
Should be straight-forward, so I'm closing this.

**Comment by maparent** [comment]
There's already a line
`-e git+https://github.com/maparent/pyodbc.git@v4-virtuoso#egg=pyodbc` in this package's requirements.txt, which should be enough.
