### ISSUE TITLE
No support for Python 3?

### ISSUE THREAD

**Issue by mfrager** [maparent/virtuoso-python#9]
File "/opt/rh/rh-python35/root/usr/lib/python3.5/site-packages/virtuoso-0.12.6-py3.5.egg/virtuoso/vstore.py", line 368
    except Exception, e:
                    ^
SyntaxError: invalid syntax

**Comment by maparent** [comment]
Correct, Python 3 was out of scope when I last worked on this.
Are you interested in taking this project over?
I am not working on it much anymore (though I would try to simplify some aspects before handing it over.)

**Comment by mfrager** [comment]
It's possible. Let me do some more testing and follow up with you. We will try to get it running on Python 3. If we can we'll post a merge request back here.

**Comment by VitorSDDF** [comment]
I also need to use vigoroso with python3.Have you made any progress on it?How big is the trouble to make  it work in python3 ?

**Comment by maparent** [comment]
Good day.
The trouble is finding a maintainer for the project willing to do this, as it is not a project I am maintaining anymore. I have made no progress and have no intention of making any.
I will, however, offer help to ease handover to whoever wants it.
I could also consider a contract if you really need it. Or you could ask the original author.
Regards

**Comment by VitorSDDF** [comment]
Good day.

I Have the options of use Java or get engaged on this.I prefer python3 but before doing this I want to have an idea of how much work/time I would spend on making it work in python3.

Regards

**Comment by maparent** [comment]
1. One of us would spend some time porting my changes to pyodbc to the latest pyodbc; I'm way behind, and I think that this has py3 impact. The changes are localized and easy to port, but need a fair amount of testing, which would be hard to delegate, but maybe doable.
What I might do is simply make the branch and hand it over after some initial testing?

2. Besides my old pyodbc, other dependencies are Py3 ready. So it should be rather light. The futurize patch is not big. But getting unicode/string right will require being careful, as we cannot just assume everything is unicode when talking to the database.

3. the vmapping class is complicated, and I was in the process of abstracting it out. I should finish that before handover. Most users of the library would not need it, so porting it to python3 is not as urgent.

I am curious if @mfrager did any progress on their side? It would be good to ask.
What's your timeframe? Cleaning my end before handover is something I thought I'd do at leisure, and if you're in a rush I cannot promise responsiveness, as I'm very busy with other projects. OTH, I do want to hand this over cleanly.

**Comment by maparent** [comment]
OK. Much progress. 
1. I have created a fresh virtuoso branch of pyodbc based on version 4. (v4-virtuoso)
3. I have separated the mapping.py and quadextractor.py in another module, so as to develop it with minimum impact on virtuoso. I might also remove vmapping at some point, but that depends on the next maintainer.

I have created a branch of this project (pyodbc4) that uses those new packages, and, after much painstaking work, all tests pass on python2.
I'll actually give the python3 port a go myself, but I feel much better about handing the project to someone else at this point.

**Comment by maparent** [comment]
Python 3 port passes tests on v4-virtuoso branch. @VitorSDDF @pchampin @mfrager please test? I will merge into master next week unless I have new bug reports.
Regards.

**Comment by pchampin** [comment]
No regression to signal on my side.

**Comment by maparent** [comment]
OK, pushed to master.
